services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    build:
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ../:/var/www/docker-template

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:17
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
